export type AppPage =
  | 'landing'
  | 'triage'
  | 'dashboard'
  | 'analytics'
  | 'clinical_reports'
  | 'care_alerts'
  | 'care_support'
  | 'ledger_monitoring'
  | 'intake_monitoring'
  | 'security'
  | 'user_management'
  | 'admin'
  | 'admin_login'
  | 'login'
  | 'forgot_password'
  | 'signup'
