export type AppPage =
  | 'landing'
  | 'appointments'
  | 'doctor_dashboard'
  | 'admin'
  | 'admin_login'
  | 'doctor_login'
  | 'login'
  | 'otp'
  | 'forgot_password'
  | 'signup'
  | 'doctor_signup'
